// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: music_service.proto

package music_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 短信发送
type SendSmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=Source,proto3" json:"Source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsRequest) Reset() {
	*x = SendSmsRequest{}
	mi := &file_music_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsRequest) ProtoMessage() {}

func (x *SendSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_music_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsRequest.ProtoReflect.Descriptor instead.
func (*SendSmsRequest) Descriptor() ([]byte, []int) {
	return file_music_service_proto_rawDescGZIP(), []int{0}
}

func (x *SendSmsRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *SendSmsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type SendSmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsResponse) Reset() {
	*x = SendSmsResponse{}
	mi := &file_music_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsResponse) ProtoMessage() {}

func (x *SendSmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_music_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsResponse.ProtoReflect.Descriptor instead.
func (*SendSmsResponse) Descriptor() ([]byte, []int) {
	return file_music_service_proto_rawDescGZIP(), []int{1}
}

// 登录注册
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	SendSms       string                 `protobuf:"bytes,2,opt,name=SendSms,proto3" json:"SendSms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_music_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_music_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_music_service_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginRequest) GetSendSms() string {
	if x != nil {
		return x.SendSms
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_music_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_music_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_music_service_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_music_service_proto protoreflect.FileDescriptor

const file_music_service_proto_rawDesc = "" +
	"\n" +
	"\x13music_service.proto\x12\rmusic_service\"B\n" +
	"\x0eSendSmsRequest\x12\x18\n" +
	"\aAccount\x18\x01 \x01(\tR\aAccount\x12\x16\n" +
	"\x06Source\x18\x02 \x01(\tR\x06Source\"\x11\n" +
	"\x0fSendSmsResponse\"B\n" +
	"\fLoginRequest\x12\x18\n" +
	"\aAccount\x18\x01 \x01(\tR\aAccount\x12\x18\n" +
	"\aSendSms\x18\x02 \x01(\tR\aSendSms\"'\n" +
	"\rLoginResponse\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId2\x9d\x01\n" +
	"\rMusic_service\x12H\n" +
	"\aSendSms\x12\x1d.music_service.SendSmsRequest\x1a\x1e.music_service.SendSmsResponse\x12B\n" +
	"\x05Login\x12\x1b.music_service.LoginRequest\x1a\x1c.music_service.LoginResponseB\x11Z\x0f./music_serviceb\x06proto3"

var (
	file_music_service_proto_rawDescOnce sync.Once
	file_music_service_proto_rawDescData []byte
)

func file_music_service_proto_rawDescGZIP() []byte {
	file_music_service_proto_rawDescOnce.Do(func() {
		file_music_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_music_service_proto_rawDesc), len(file_music_service_proto_rawDesc)))
	})
	return file_music_service_proto_rawDescData
}

var file_music_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_music_service_proto_goTypes = []any{
	(*SendSmsRequest)(nil),  // 0: music_service.SendSmsRequest
	(*SendSmsResponse)(nil), // 1: music_service.SendSmsResponse
	(*LoginRequest)(nil),    // 2: music_service.LoginRequest
	(*LoginResponse)(nil),   // 3: music_service.LoginResponse
}
var file_music_service_proto_depIdxs = []int32{
	0, // 0: music_service.Music_service.SendSms:input_type -> music_service.SendSmsRequest
	2, // 1: music_service.Music_service.Login:input_type -> music_service.LoginRequest
	1, // 2: music_service.Music_service.SendSms:output_type -> music_service.SendSmsResponse
	3, // 3: music_service.Music_service.Login:output_type -> music_service.LoginResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_music_service_proto_init() }
func file_music_service_proto_init() {
	if File_music_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_music_service_proto_rawDesc), len(file_music_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_music_service_proto_goTypes,
		DependencyIndexes: file_music_service_proto_depIdxs,
		MessageInfos:      file_music_service_proto_msgTypes,
	}.Build()
	File_music_service_proto = out.File
	file_music_service_proto_goTypes = nil
	file_music_service_proto_depIdxs = nil
}
