// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type HelloReq struct {
	Name string `path:"name"`
}

type HelloResp struct {
	Message string `json:"message"`
}

type PingReq struct {
}

type PingResp struct {
}

type Response struct {
	Code int                    `json:"code"`
	Msg  string                 `json:"msg"`
	Data map[string]interface{} `json:"data"`
}
