// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: music_service.proto

package server

import (
	"context"

	"Music_service/internal/logic"
	"Music_service/internal/svc"
	"Music_service/music_service"
)

type MusicServiceServer struct {
	svcCtx *svc.ServiceContext
	music_service.UnimplementedMusicServiceServer
}

func NewMusicServiceServer(svcCtx *svc.ServiceContext) *MusicServiceServer {
	return &MusicServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MusicServiceServer) SendSms(ctx context.Context, in *music_service.SendSmsRequest) (*music_service.SendSmsResponse, error) {
	l := logic.NewSendSmsLogic(ctx, s.svcCtx)
	return l.SendSms(in)
}

func (s *MusicServiceServer) Login(ctx context.Context, in *music_service.LoginRequest) (*music_service.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
